### ISSUE TITLE
How to convert lama to onnx？

### ISSUE THREAD

**Issue by darengking** [ZHEQIUSHUI/SAM-AX650#1]
When I try to convert lama model to onnx,  i got `RuntimeError: Exporting the operator fft_rfftn to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.`  Wonld you please tell me how did you solve this issue? thank you.

**Comment by ZHEQIUSHUI** [comment]
update your pytorch to nightly version

**Comment by darengking** [comment]
Thank you.

**Comment by kylechang523** [comment]
Hi, may I ask where is the script to covert the Lama model to onnx? Thank you

**Comment by ZHEQIUSHUI** [comment]
> Hi, may I ask where is the script to covert the Lama model to onnx? Thank you

https://github.com/ZHEQIUSHUI/lama

**Comment by matpaul** [comment]
> update your pytorch to nightly version

Hello,
I use night version (2.2.0.dev20231022) but there is same issue
```
Prediction failed due to Exporting the operator 'aten::fft_rfftn' to ONNX opset version 17 is not supported.
```
Could you help ?

**Comment by ZHEQIUSHUI** [comment]
> > update your pytorch to nightly version
> 
> Hello,
> I use night version (2.2.0.dev20231022) but there is same issue
> ```
> Prediction failed due to Exporting the operator 'aten::fft_rfftn' to ONNX opset version 17 is not supported.
> ```
> Could you help ?

fft is not support export onnx model，I use big-lama-regular（resnet backbone？） version pretrain model
